# Notebook 1 - Python for GenAI: Refresher, NumPy, Pandas, Data Cleaning, File Handling

This notebook covers the foundational Python and data-handling skills used throughout the rest of the
course. It is organised into four parts:

1. Python refresher (syntax, functions, comprehensions, classes)
2. NumPy (numerical arrays and vectorised computation)
3. Pandas (tabular data manipulation)
4. Data cleaning (handling messy, real-world-like data)
5. File handling (reading and writing text, CSV and JSON files)

This notebook is written to run top to bottom in Google Colab with no extra setup required, since it
only uses libraries that ship with Colab by default (`numpy`, `pandas`, `os`, `json`, `csv`).


## 1. Python Refresher

A quick recap of the Python building blocks we will rely on for the rest of the course: variables and
data types, control flow, functions, comprehensions, and a minimal class example.


In [1]:
# Variables and core data types
name = "GenAI Learner"
age = 25
height_m = 1.75
is_enrolled = True
skills = ["python", "numpy", "pandas"]
profile = {"name": name, "age": age, "skills": skills}

print(type(name), type(age), type(height_m), type(is_enrolled), type(skills), type(profile))
print(profile)


<class 'str'> <class 'int'> <class 'float'> <class 'bool'> <class 'list'> <class 'dict'>
{'name': 'GenAI Learner', 'age': 25, 'skills': ['python', 'numpy', 'pandas']}


In [2]:
# Control flow: if / for / while
for skill in skills:
    if skill.startswith("p"):
        print(skill, "-> starts with p")
    else:
        print(skill, "-> does not start with p")

count = 0
while count < 3:
    print("while loop iteration:", count)
    count += 1


python -> starts with p
numpy -> does not start with p
pandas -> starts with p
while loop iteration: 0
while loop iteration: 1
while loop iteration: 2


In [3]:
# Functions: default args, *args, **kwargs, lambda
def describe_person(name, age=18, **extra_info):
    base = f"{name} is {age} years old."
    if extra_info:
        details = ", ".join(f"{k}={v}" for k, v in extra_info.items())
        base += f" Extra: {details}"
    return base

print(describe_person("Ahmed", age=30, role="Instructor", city="Bengaluru"))

def total(*numbers):
    return sum(numbers)

print("total:", total(1, 2, 3, 4, 5))

square = lambda x: x ** 2
print("square(7) =", square(7))


Ahmed is 30 years old. Extra: role=Instructor, city=Bengaluru
total: 15
square(7) = 49


In [4]:
# Comprehensions: list, dict, set
numbers = list(range(1, 11))

squares = [n ** 2 for n in numbers]
even_squares = [n ** 2 for n in numbers if n % 2 == 0]
square_lookup = {n: n ** 2 for n in numbers}
unique_remainders = {n % 3 for n in numbers}

print("squares:", squares)
print("even_squares:", even_squares)
print("square_lookup:", square_lookup)
print("unique_remainders:", unique_remainders)


squares: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
even_squares: [4, 16, 36, 64, 100]
square_lookup: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}
unique_remainders: {0, 1, 2}


In [5]:
# A minimal class example
class Student:
    """Represents a student on the course."""

    def __init__(self, name, scores):
        self.name = name
        self.scores = scores

    def average_score(self):
        return sum(self.scores) / len(self.scores)

    def __repr__(self):
        return f"Student(name={self.name!r}, average={self.average_score():.2f})"


students = [Student("Asha", [88, 92, 79]), Student("Ravi", [65, 70, 72])]
for s in students:
    print(s)


Student(name='Asha', average=86.33)
Student(name='Ravi', average=69.00)


## 2. NumPy

NumPy is the core library for fast numerical computation in Python. Pandas, scikit-learn and most
machine learning libraries are built on top of it.


In [6]:
import numpy as np

# Creating arrays
a = np.array([1, 2, 3, 4, 5])
b = np.arange(0, 10, 2)          # start, stop, step
c = np.linspace(0, 1, 5)         # 5 evenly spaced points between 0 and 1
zeros = np.zeros((2, 3))
ones = np.ones((3, 2))
identity = np.eye(3)

print("a:", a)
print("b:", b)
print("c:", c)
print("zeros:\n", zeros)
print("identity:\n", identity)
print("a dtype/shape:", a.dtype, a.shape)


a: [1 2 3 4 5]
b: [0 2 4 6 8]
c: [0.   0.25 0.5  0.75 1.  ]
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
a dtype/shape: int64 (5,)


In [7]:
# Indexing, slicing and boolean masking
matrix = np.arange(1, 13).reshape(3, 4)
print("matrix:\n", matrix)

print("first row:", matrix[0])
print("second column:", matrix[:, 1])
print("sub-matrix:\n", matrix[0:2, 1:3])

mask = matrix % 2 == 0
print("even mask:\n", mask)
print("even values:", matrix[mask])


matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
first row: [1 2 3 4]
second column: [ 2  6 10]
sub-matrix:
 [[2 3]
 [6 7]]
even mask:
 [[False  True False  True]
 [False  True False  True]
 [False  True False  True]]
even values: [ 2  4  6  8 10 12]


In [8]:
# Vectorised operations and broadcasting
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

print("x + y:", x + y)
print("x * 2:", x * 2)
print("dot product:", np.dot(x, y))

# Broadcasting: adding a (3,) vector to every row of a (3,3) matrix
grid = np.ones((3, 3))
print("grid + x:\n", grid + x)


x + y: [11 22 33]
x * 2: [2 4 6]
dot product: 140
grid + x:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [9]:
# Aggregations and random numbers
rng = np.random.default_rng(seed=42)
sample = rng.normal(loc=50, scale=10, size=1000)

print("mean:", sample.mean())
print("std:", sample.std())
print("min/max:", sample.min(), sample.max())
print("argmax index:", sample.argmax())


mean: 49.711084490040534
std: 9.88722355396508
min/max: 13.515871747852167 81.78853679367535
argmax index: 846


## 3. Pandas

Pandas gives us `Series` (1-D labelled arrays) and `DataFrame` (2-D labelled tables), which are the
standard way to work with structured/tabular data in Python.


In [10]:
import pandas as pd

# Series and DataFrame creation
s = pd.Series([10, 20, 30, 40], name="scores")
print(s)

df = pd.DataFrame({
    "name": ["Asha", "Ravi", "Meera", "Kiran"],
    "age": [23, 25, 22, 28],
    "department": ["Data", "AI", "Data", "AI"],
    "score": [88, 74, 91, 67],
})
df


0    10
1    20
2    30
3    40
Name: scores, dtype: int64


,name,age,department,score
0,Asha,23,Data,88
1,Ravi,25,AI,74
2,Meera,22,Data,91
3,Kiran,28,AI,67


In [11]:
# Writing to and reading from CSV
df.to_csv("students.csv", index=False)
loaded_df = pd.read_csv("students.csv")
loaded_df


,name,age,department,score
0,Asha,23,Data,88
1,Ravi,25,AI,74
2,Meera,22,Data,91
3,Kiran,28,AI,67


In [12]:
# Indexing and filtering
print(df.loc[0, "name"])          # label based
print(df.iloc[0, 0])              # position based

high_scorers = df[df["score"] >= 80]
high_scorers


Asha
Asha


,name,age,department,score
0,Asha,23,Data,88
2,Meera,22,Data,91


In [13]:
# Groupby and aggregation
dept_summary = df.groupby("department")["score"].agg(["mean", "min", "max", "count"])
dept_summary


,mean,min,max,count
department,,,,
AI,70.5,67,74,2
Data,89.5,88,91,2


In [14]:
# Merge / join and sorting
extra_info = pd.DataFrame({
    "name": ["Asha", "Ravi", "Meera", "Kiran"],
    "city": ["Bengaluru", "Hyderabad", "Chennai", "Pune"],
})

merged = pd.merge(df, extra_info, on="name")
sorted_df = merged.sort_values("score", ascending=False)
sorted_df


,name,age,department,score,city
2,Meera,22,Data,91,Chennai
0,Asha,23,Data,88,Bengaluru
1,Ravi,25,AI,74,Hyderabad
3,Kiran,28,AI,67,Pune


In [15]:
# value_counts and concat
print(df["department"].value_counts())

more_students = pd.DataFrame({
    "name": ["Farah", "Zoya"],
    "age": [24, 26],
    "department": ["AI", "Data"],
    "score": [95, 60],
})

combined = pd.concat([df, more_students], ignore_index=True)
combined


department
Data    2
AI      2
Name: count, dtype: int64


,name,age,department,score
0,Asha,23,Data,88
1,Ravi,25,AI,74
2,Meera,22,Data,91
3,Kiran,28,AI,67
4,Farah,24,AI,95
5,Zoya,26,Data,60


## 4. Data Cleaning

Real-world data is rarely as clean as the table above. Here we build a small, deliberately messy
dataset (missing values, duplicates, inconsistent text, and an outlier) and clean it step by step.


In [16]:
messy_df = pd.DataFrame({
    "name": [" Asha", "ravi", "Meera ", "Kiran", "Kiran", "Farah", None],
    "age": [23, 25, np.nan, 28, 28, 150, 24],       # 150 is an unrealistic outlier
    "department": ["Data", "ai", "Data", "AI", "AI", "Data", "Data"],
    "score": [88, 74, 91, np.nan, 67, 95, 60],
})
messy_df


,name,age,department,score
0,Asha,23.0,Data,88.0
1,ravi,25.0,ai,74.0
2,Meera,NaN,Data,91.0
3,Kiran,28.0,AI,NaN
4,Kiran,28.0,AI,67.0
5,Farah,150.0,Data,95.0
6,NaN,24.0,Data,60.0


In [17]:
# Step 1: inspect missing values
print(messy_df.isna().sum())


name          1
age           1
department    0
score         1
dtype: int64


In [18]:
# Step 2: handle missing values
clean_df = messy_df.copy()

# Fill missing numeric columns with the column median
clean_df["score"] = clean_df["score"].fillna(clean_df["score"].median())
clean_df["age"] = clean_df["age"].fillna(clean_df["age"].median())

# Drop rows where the name itself is missing, since we cannot recover that
clean_df = clean_df.dropna(subset=["name"])

clean_df


,name,age,department,score
0,Asha,23.0,Data,88.0
1,ravi,25.0,ai,74.0
2,Meera,26.5,Data,91.0
3,Kiran,28.0,AI,81.0
4,Kiran,28.0,AI,67.0
5,Farah,150.0,Data,95.0


In [19]:
# Step 3: remove duplicate rows (Kiran appears twice with identical data)
clean_df = clean_df.drop_duplicates()
clean_df


,name,age,department,score
0,Asha,23.0,Data,88.0
1,ravi,25.0,ai,74.0
2,Meera,26.5,Data,91.0
3,Kiran,28.0,AI,81.0
4,Kiran,28.0,AI,67.0
5,Farah,150.0,Data,95.0


In [20]:
# Step 4: standardise inconsistent text (extra spaces, mixed case)
clean_df["name"] = clean_df["name"].str.strip().str.title()
clean_df["department"] = clean_df["department"].str.strip().str.upper()
clean_df


,name,age,department,score
0,Asha,23.0,DATA,88.0
1,Ravi,25.0,AI,74.0
2,Meera,26.5,DATA,91.0
3,Kiran,28.0,AI,81.0
4,Kiran,28.0,AI,67.0
5,Farah,150.0,DATA,95.0


In [21]:
# Step 5: detect and handle outliers using the IQR method
q1 = clean_df["age"].quantile(0.25)
q3 = clean_df["age"].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

print("valid age range:", lower_bound, "to", upper_bound)
outliers = clean_df[(clean_df["age"] < lower_bound) | (clean_df["age"] > upper_bound)]
print("outlier rows:\n", outliers)

# Replace the outlier age with the median age instead of dropping the whole row
median_age = clean_df.loc[
    (clean_df["age"] >= lower_bound) & (clean_df["age"] <= upper_bound), "age"
].median()
clean_df.loc[(clean_df["age"] < lower_bound) | (clean_df["age"] > upper_bound), "age"] = median_age
clean_df


valid age range: 21.4375 to 31.9375
outlier rows:
     name    age department  score
5  Farah  150.0       DATA   95.0


,name,age,department,score
0,Asha,23.0,DATA,88.0
1,Ravi,25.0,AI,74.0
2,Meera,26.5,DATA,91.0
3,Kiran,28.0,AI,81.0
4,Kiran,28.0,AI,67.0
5,Farah,26.5,DATA,95.0


In [22]:
# Step 6: fix data types
clean_df["age"] = clean_df["age"].astype(int)
clean_df.dtypes


name              str
age             int64
department        str
score         float64
dtype: object

## 5. File Handling

Basic reading and writing of text, CSV and JSON files using Python's built-in tools. (Error handling
with `try`/`except` is intentionally left out of this notebook and covered separately.)


In [23]:
# Plain text files
with open("notes.txt", "w") as f:
    f.write("Day 2 covers AI, ML, DL and GenAI foundations.\n")
    f.write("We also build a linear regression and a small neural network.\n")

with open("notes.txt", "r") as f:
    contents = f.read()

print(contents)


Day 2 covers AI, ML, DL and GenAI foundations.
We also build a linear regression and a small neural network.



In [24]:
# CSV files with the csv module
import csv

rows = [
    {"name": "Asha", "score": 88},
    {"name": "Ravi", "score": 74},
    {"name": "Meera", "score": 91},
]

with open("scores.csv", "w", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=["name", "score"])
    writer.writeheader()
    writer.writerows(rows)

with open("scores.csv", "r") as f:
    reader = csv.DictReader(f)
    for row in reader:
        print(row)


{'name': 'Asha', 'score': '88'}
{'name': 'Ravi', 'score': '74'}
{'name': 'Meera', 'score': '91'}


In [25]:
# JSON files
import json

course_info = {
    "day": 2,
    "topics": ["AI vs ML vs DL vs GenAI", "Linear Regression", "ANN Intuition", "Clustering", "KNN"],
    "duration_hours": 4,
}

with open("course_info.json", "w") as f:
    json.dump(course_info, f, indent=2)

with open("course_info.json", "r") as f:
    loaded_info = json.load(f)

print(loaded_info)


{'day': 2, 'topics': ['AI vs ML vs DL vs GenAI', 'Linear Regression', 'ANN Intuition', 'Clustering', 'KNN'], 'duration_hours': 4}


In [26]:
# Basic file/OS operations
import os

print("current working directory:", os.getcwd())
print("files created in this notebook:")
for filename in ["notes.txt", "scores.csv", "course_info.json", "students.csv"]:
    print(" -", filename, "| exists:", os.path.exists(filename))


current working directory: /root/notebooks
files created in this notebook:
 - notes.txt | exists: True
 - scores.csv | exists: True
 - course_info.json | exists: True
 - students.csv | exists: True


### Summary

In this notebook we covered: core Python syntax and idioms, NumPy arrays and vectorised computation,
Pandas Series/DataFrames for tabular data, a practical data-cleaning workflow (missing values,
duplicates, inconsistent text, outliers, dtypes), and basic file handling for text, CSV and JSON.

These skills form the data-handling foundation used in Notebook 2 (AI/ML foundations) and
Notebook 3 (NLP basics).
